### ISSUE TITLE
can't download the pre_trained word2vec

### ISSUE THREAD

**Issue by zyn412** [shashankg7/CNN-QA#2]
i can't download the pre-initialized word2vec embedding.
i can't open that link.
Can someone help me?

**Comment by kingwmk** [comment]
hi, did you obtain the word2vec embeddings? i am have the same problem. May I ask a help? @zyn412 @shashankg7

**Comment by zyn412** [comment]
sorry，i didn’t obtain the embeddings.




------------------ 原始邮件 ------------------
发件人: "kingwmk"<notifications@github.com>; 
发送时间: 2019年4月30日(星期二) 下午4:13
收件人: "shashankg7/Keras-CNN-QA"<Keras-CNN-QA@noreply.github.com>; 
抄送: "442653057"<442653057@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [shashankg7/Keras-CNN-QA] can't download the pre_trained word2vec(#2)




hi, did you obtain the word2vec embeddings? i am have the same problem. May I ask a help? @zyn412 @shashankg7
